import type { HistorialCambio } from '../types';

export const MOCK_HISTORIAL: readonly HistorialCambio[] = [
  {
    id_historial: 1,
    fecha_hora: "2025-11-20T08:30:00",
    nombre_evaluador: "Juan Pérez",
    nombre_olimpista: "María López",
    area: "Matemáticas",
    nivel: "1ro de Secundaria",
    accion: "Calificar",
    observacion: null,
    descripcion: "Calificación inicial asignada: 85 pts.",
    id_area: 1,
    id_nivel: 101,
    nota_nueva: 85
  },
  {
    id_historial: 2,
    fecha_hora: "2025-11-20T08:45:00",
    nombre_evaluador: "Juan Pérez",
    nombre_olimpista: "José Mamani",
    area: "Matemáticas",
    nivel: "1ro de Secundaria",
    accion: "Calificar",
    observacion: null,
    descripcion: "Calificación inicial asignada: 90 pts.",
    id_area: 1,
    id_nivel: 101,
    nota_nueva: 90
  },
  {
    id_historial: 3,
    fecha_hora: "2025-11-20T09:15:00",
    nombre_evaluador: "Juan Pérez",
    nombre_olimpista: "María López",
    area: "Matemáticas",
    nivel: "1ro de Secundaria",
    accion: "Modificar",
    observacion: "Error de tipeo en la pregunta 3, se verificó la hoja de respuestas.",
    descripcion: "Nota modificada de 85 a 95 pts.",
    id_area: 1,
    id_nivel: 101,
    nota_anterior: 85,
    nota_nueva: 95
  },
  {
    id_historial: 4,
    fecha_hora: "2025-11-21T10:00:00",
    nombre_evaluador: "Carlos Ruiz",
    nombre_olimpista: "Pedro Pascal",
    area: "Física",
    nivel: "Nivel Avanzado",
    accion: "Desclasificar",
    observacion: "Uso de calculadora programable no permitida según reglamento Art. 4.",
    descripcion: "Participante desclasificado. Nota anulada.",
    id_area: 2,
    id_nivel: 302,
    nota_anterior: 70,
    nota_nueva: 0
  },
  {
    id_historial: 5,
    fecha_hora: "2025-11-22T14:20:00",
    nombre_evaluador: "Ana Gómez",
    nombre_olimpista: "Roberto Carlos",
    area: "Robótica",
    nivel: "Categoría A (Constructores)",
    accion: "Calificar",
    observacion: "Excelente desempeño en pista, cumplió el reto en tiempo récord.",
    descripcion: "Calificación inicial asignada: 100 pts.",
    id_area: 3,
    id_nivel: 201,
    nota_nueva: 100
  },
  {
    id_historial: 6,
    fecha_hora: "2025-11-23T11:45:00",
    nombre_evaluador: "Luis Fernández",
    nombre_olimpista: "Carla Bruni",
    area: "Química",
    nivel: "6to de Secundaria",
    accion: "Modificar",
    observacion: "Revisión de reclamo procedente. Se valida el procedimiento del ejercicio 2.",
    descripcion: "Nota modificada de 60 a 65 pts.",
    id_area: 4,
    id_nivel: 106,
    nota_anterior: 60,
    nota_nueva: 65
  },
  {
    id_historial: 7,
    fecha_hora: "2025-11-20T15:00:00",
    nombre_evaluador: "Juan Pérez",
    nombre_olimpista: "Sofía Vergara",
    area: "Matemáticas",
    nivel: "2do de Secundaria",
    accion: "Calificar",
    observacion: null,
    descripcion: "Calificación inicial asignada: 40 pts.",
    id_area: 1,
    id_nivel: 102,
    nota_nueva: 40
  },
  {
    id_historial: 8,
    fecha_hora: "2025-11-20T16:30:00",
    nombre_evaluador: "Juan Pérez",
    nombre_olimpista: "Sofía Vergara",
    area: "Matemáticas",
    nivel: "2do de Secundaria",
    accion: "Modificar",
    observacion: "Suma incorrecta en el total parcial.",
    descripcion: "Nota modificada de 40 a 45 pts.",
    id_area: 1,
    id_nivel: 102,
    nota_anterior: 40,
    nota_nueva: 45
  }
];